---
title: "learn GAM"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
mcycle <- MASS::mcycle

library(mgcv)

# Fit a GAM with 3 basis functions
gam_mod_k3 <- gam(accel ~ s(times, k = 3), data = mcycle)

# Fit with 20 basis functions
gam_mod_k20 <- gam(accel ~ s(times, k= 20), data = mcycle)

# Visualize the GAMs
par(mfrow = c(1, 2))
plot(gam_mod_k3, residuals = TRUE, pch = 1)
plot(gam_mod_k20, residuals = TRUE, pch = 1)
```
```{r}
# Extract the smoothing parameter
gam_mod <- gam(accel ~ s(times), data = mcycle, method = "REML")

summary(gam_mod)

# Fix the smoothing parameter at 0.1
gam_mod_s1 <- gam(accel ~ s(times), data = mcycle, sp = 0.1)

# Fix the smoothing parameter at 0.0001
gam_mod_s2 <- gam(accel ~ s(times), data = mcycle, sp = 0.0001)

# Plot both models
par(mfrow = c(2, 1))
plot(gam_mod_s1, residuals = TRUE, pch = 1)
plot(gam_mod_s2, residuals = TRUE, pch = 1)
```
```{r}
gam_mod$sp
```
```{r}
# Fit the GAM
gam_mod_sk <- gam(data = mcycle, accel ~ s(times, k = 50, sp = 0.0001)) 

# Visualize the model
plot(gam_mod_sk, residuals = TRUE, pch = 1)
```
```{r}
library(gamair)
data("mpg", package="gamair")
```
```{r}
head(mpg)
tail(mpg)
```
```{r}
# Fit the model
mod_city <- gam(city.mpg ~ s(weight) + s(length) + s(price), 
                data = mpg, method = "REML")
```
```{r}
# Plot the model
plot(mod_city, pages = 1)
```
```{r}
# Fit the model
mod_city2 <- gam(city.mpg ~ s(weight) + s(length) + s(price) + fuel + drive + style, 
                 data = mpg, method = "REML")

# Plot the model
plot(mod_city2, all.terms = TRUE, pages = 1)
```
```{r}
# Fit the model
mod_city3 <- gam(city.mpg ~ s(weight, by=drive) + s(length, by=drive) + s(price, by=drive), 
                 data = mpg, method = "REML")

# Plot the model
plot(mod_city3, pages = 1)
```

```{r}
library(gamair)
set.seed(0)
data("mpg", package="gamair", verbose=FALSE)

library(mgcv)
# Fit the model
mod <- gam(hw.mpg ~ s(length) + s(width) + s(height) + s(weight),
           data = mpg, method = "REML")


 ```

```{r}
# Check overall concurvity
concurvity(mod)
```
```{r}
library(tidyverse)
```

```{r}
# Fit the model
mod <- gam(hw.mpg ~ s(length) + s(width) + s(height) + s(weight),
           data = mpg, method = "REML")

# Check pairwise concurvity
map(concurvity(mod, full = F), round, digits = 2)
```
```{r}
concurvity(mod, full = F) %>% 
  map(~round(., digits = 2))
```

```{r}
tmp <- smoothCon(s(length), data = mpg)
```

